apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: devsecops-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: ghcr.io/anisfrj/flask-api:9a67158b82c74b7562b35c0077886d42a03bd92b
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: flask-config
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
